# Generated by Django 4.1 on 2022-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpsdiseasesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='snp2phenotype2ref',
            name='genes',
            field=models.ManyToManyField(to='snpsdiseasesapp.genes'),
        ),
    ]
