# Generated by Django 4.1 on 2022-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpsdiseasesapp', '0003_alter_snp2phenotype2ref_genes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp2phenotype2ref',
            name='genes',
            field=models.ManyToManyField(blank=True, to='snpsdiseasesapp.genes'),
        ),
    ]
