# Generated by Django 4.1 on 2022-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpsdiseasesapp', '0004_alter_snp2phenotype2ref_genes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='chrom_pos',
            field=models.IntegerField(max_length=50),
        ),
    ]
