# Generated by Django 4.1 on 2022-11-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snpsdiseasesapp', '0005_alter_snp_chrom_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='chrom_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
